# https://github.com/noahgorstein/jqp
theme:
  ## Light Themes
  # name: "abap"
  # name: "algol"
  # name: "arduino"
  # name: "autumn"
  # name: "borland"
  # name: "colorful"
  # name: "emacs"
  # name: "friendly"
  # name: "github"
  # name: "gruvbox-light"
  # name: "hrdark"
  # name: "igor"
  # name: "lovelace"
  # name: "manni"
  # name: "monokai-light"
  # name: "murphy"
  # name: "onesenterprise"
  # name: "paradaiso-light"
  # name: "pastie"
  # name: "perldoc"
  # name: "pygments"
  # name: "solarized-light"
  # name: "tango"
  # name: "trac"
  # name: "visual_studio"
  # name: "vulcan"
  # name: "xcode"
  ## Dark Themes
  # name: "average"
  # name: "base16snazzy"
  # name: "doom-onep"
  # name: "doom-one2"
  name: "dracula"
  # name: "fruity"
  # name: "github-dark"
  # name: "gruvbox"
  # name: "monokai"
  # name: "native"
  # name: "paradaiso-dark"
  # name: "rrt"
  # name: "solarized-dark"
  # name: "solarized-dark256"
  # name: "swapoff"
  # name: "vim"
  # name: "witchhazel"
  # name: "xcode-dark"
  chromaStyleOverrides: # override parts of the chroma style
    kc: "#009900 underline" # keys use the chroma short names
