#!/usr/bin/env bash

script_id="mbrav/dotfiles installer"
script_dir="$(dirname "$(realpath "$0")")"
dot_dir="$(realpath "${script_dir}/../../../")"

## install soft
sudo apt install curl git fonts-firacode fzf gpg -y
## install starship
curl -fsSL https://starship.rs/install.sh | sh
## install  mcfly
curl -LSfs https://raw.githubusercontent.com/cantino/mcfly/master/ci/install.sh | sh -s -- --git cantino/mcfly
## install eza
sudo mkdir -p /etc/apt/keyrings
wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
sudo apt update
sudo apt install -y eza
## install fish
echo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_12/ /' | sudo tee /etc/apt/sources.list.d/shells:fish:release:3.list
curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:3/Debian_12/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg > /dev/null
sudo apt update
sudo apt install fish
chsh -s $(which fish)
## install bat
wget https://github.com/sharkdp/bat/releases/download/v0.24.0/bat_0.24.0_amd64.deb && dpkg -i bat_0.24.0_amd64.deb

# Source util functions
source "${script_dir}/_util"

function dotfiles_symlink() {
	# List conf files in .config
	local dir_ls=($(ls -A "$dot_dir/dotfiles/.config"))

	# Loop through contents
	for item in "${dir_ls[@]}"; do
		# Check item full path
		local item_path="$dot_dir/dotfiles/.config/$item"
		if [ -f $item_path ] || [ -d $item_path ] && [ -z "$force" ]; then
			info_msg "Item $item_path exists"
			yes_no_prompt "${GREEN}Replace $item_path with new symlink?${YELLOW}" &&
				rm -rfv "$HOME/.config/$item" &&
				ln -sv "$item_path" "$HOME/.config/$item"
		else
			info_msg "Symlinking file $item_path to $HOME/.config/$item"
			rm -rfv "$HOME/.config/$item"
			ln -sv "$item_path" "$HOME/.config/$item"
		fi
	done

	# List conf files in home
	local dir_ls=(".bashrc" ".gitconfig" ".stignore" ".vimrc" ".vimrc.plug" ".jqp.yaml")

	for item in "${dir_ls[@]}"; do
		local item_path="$dot_dir/dotfiles/$item"
		if [ -f $item_path ] || [ -d $item_path ] && [ -z "$force" ]; then
			info_msg "Item $item_path exists"
			yes_no_prompt "${GREEN}Replace $item_path with new symlink?${YELLOW}" &&
				rm -fv "$HOME/$item" &&
				ln -sv "$item_path" "$HOME/$item"
		else
			info_msg "Symlinking file $item_path to $HOME/$item"
			rm -fv "$HOME/$item"
			ln -sv "$item_path" "$HOME/$item"
		fi
	done
}

ran_col_str "${script_id} installer"
if [[ -z "$force" ]]; then
	warning_msg "Script in interative mode. Use force=1 ./install.sh for non-interactive install"
	yes_no_prompt "${GREEN}Install Dotfiles as symlinks? ${YELLOW}" &&
		dotfiles_symlink
else
	info_msg "Installing dotfiles non-interactively"
	dotfiles_symlink
fi

[[ $? -ne 0 ]] && error_msg "Failed to install dotfiles" 1 ||
	success_msg "Dotfiles install successfuly! Reload shell."

exit 0
